"""First revision

Revision ID: 8e8cb463a2de
Revises: 
Create Date: 2024-01-31 17:43:23.331619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8cb463a2de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kakao_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('kakao_access_token', sa.String(length=255), nullable=False),
    sa.Column('kakao_refresh_token', sa.String(length=255), nullable=False),
    sa.Column('jwt_refresh_token', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_diet_plan_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto Increment'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Auto Increment'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto Increment'),
    sa.Column('user_diet_plan_info_id', sa.Integer(), nullable=True, comment='Auto Increment'),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('recommended_exercise', sa.Text(), nullable=True),
    sa.Column('excess_calories', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_diet_plan_info_id'], ['user_diet_plan_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto Increment'),
    sa.Column('user_diet_plan_info_id', sa.Integer(), nullable=False, comment='Auto Increment'),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('meal_time', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_diet_plan_info_id'], ['user_diet_plan_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    op.drop_table('exercise')
    op.drop_table('user_diet_plan_info')
    op.drop_table('user')
    # ### end Alembic commands ###
