"""Add tables for V2

Revision ID: f0924d7ae838
Revises: 8e8cb463a2de
Create Date: 2024-02-03 11:07:19.939581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.session import insp

# revision identifiers, used by Alembic.
revision: str = 'f0924d7ae838'
down_revision: Union[str, None] = '8e8cb463a2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kakao_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('kakao_access_token', sa.String(length=255), nullable=False),
    sa.Column('kakao_refresh_token', sa.String(length=255), nullable=False),
    sa.Column('jwt_refresh_token', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_diet_plan_info_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto Increment'),
    sa.Column('user_v2_id', sa.Integer(), nullable=False, comment='Auto Increment'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('advice', sa.TEXT(), nullable=True),
    sa.Column('recommanded_exercise', sa.TEXT(), nullable=True),
    sa.Column('excess_calories', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_v2_id'], ['user_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto Increment'),
    sa.Column('user_diet_plan_info_v2_id', sa.Integer(), nullable=False, comment='Auto Increment'),
    sa.Column('my_exercise', sa.String(255), nullable=True),
    sa.Column('my_exercise_calories', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_diet_plan_info_v2_id'], ['user_diet_plan_info_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto Increment'),
    sa.Column('user_diet_plan_info_v2_id', sa.Integer(), nullable=False, comment='Auto Increment'),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('car', sa.Float(), nullable=True),
    sa.Column('pro', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('meal_time', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_diet_plan_info_v2_id'], ['user_diet_plan_info_v2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # table_list = insp.get_table_names()
    op.drop_table('menu_v2')
    op.drop_table('exercise_v2')
    op.drop_table('user_diet_plan_info_v2')
    op.drop_table('user_v2')
    # ### end Alembic commands ###
