"""Initial migration

Revision ID: fb93d37d6676
Revises: 
Create Date: 2024-01-17 09:23:53.269284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb93d37d6676'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Exercise',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='Auto Increment'),
    sa.Column('user_diet_plan_info_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='Auto Increment'),
    sa.Column('advice', mysql.TEXT(), nullable=True),
    sa.Column('recommended_exercise', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_diet_plan_info_id'], ['UserDietPlanInfo.id'], name='Exercise_ibfk_1'),
    sa.PrimaryKeyConstraint('id', 'user_diet_plan_info_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('UserDietPlanInfo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='Auto Increment'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='Auto Increment'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='UserDietPlanInfo_ibfk_1'),
    sa.PrimaryKeyConstraint('id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='Auto Increment'),
    sa.Column('kakao_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('height', mysql.FLOAT(), nullable=True),
    sa.Column('weight', mysql.FLOAT(), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('target_weight', mysql.FLOAT(), nullable=True),
    sa.Column('kakao_access_token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('kakao_refresh_token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('jwt_refresh_token', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Menus',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='Auto Increment'),
    sa.Column('user_diet_plan_info_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='Auto Increment'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('calories', mysql.FLOAT(), nullable=True),
    sa.Column('meal_time', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_diet_plan_info_id'], ['UserDietPlanInfo.id'], name='Menus_ibfk_1'),
    sa.PrimaryKeyConstraint('id', 'user_diet_plan_info_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Menus')
    op.drop_table('Users')
    op.drop_table('UserDietPlanInfo')
    op.drop_table('Exercise')
    # ### end Alembic commands ###
