name: Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
      
    - name: Login to Dockerhub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/foodteacher-be:${{ github.sha }}
        
    - name: Update docker image name
      run: |
        git init
        git config --global user.email "gracehpark@naver.com"
        git config --global user.name "gracehpark0120"
        git clone https://${{ secrets.GIT_TOKEN }}@github.com/foodteacher/devops.git
        cd devops/be
        sed -i "s|gracehpark/foodteacher-be:.*|gracehpark/foodteacher-be:${{ github.sha }}|g" be-deployment.yaml
        git commit -am "Update Docker Image Name"
        git push
